'use client';

import './globals.css';
import type { Metadata } from 'next';
import { store } from '@/lib/store/store';
import { Provider } from 'react-redux/es/exports';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return <Provider store={store}>{children}</Provider>;
}
